angleKp: 1.0
angleKd: 0.0
speedKp: 1.0
speedKd: 0.0
constantSpeed: 0.6
cornerSpeed: 0.3
parkingDistance: 0.05
hue_min: 0
hue_max: 35
saturation: 150
value: 100
timeout: 5000
corner: 100
erosion: 1
dilation: 5
